version: '3.7'

services:
  client:
    container_name: pds-dashboard-admin-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - ${PORT}:${PORT}
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true