version: '3.7'

services:
  pds-dashboard-admin:
    container_name: default
    env_file: .env.production
    build:
      context: .
      dockerfile: Dockerfile-prod
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - ${DEFAULT_PORT}:3000
    stdin_open: true
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${IPAM_CONFIG_SUBNET_ADMIN_DASHBOARD}