version: '3.7'

services:
  client:
    container_name: pds-dashboard-admin
    env_file: .env.production
    build:
      context: .
      dockerfile: Dockerfile-prod
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 443:443
    stdin_open: true

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${IPAM_CONFIG_SUBNET_ADMIN_DASHBOARD}
