version: '3.7'

services:
  pds-dashboard-admin:
    container_name: pds-dashboard-admin
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8081:3000
    stdin_open: true