version: '3.7'

services:

  pds-dashboard-admin:
    container_name: pds-dashboard-admin
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${IPAM_CONFIG_SUBNET}