export const SET_CONFIG = "SET_CONFIG";
export const SET_SELECTORS = "SET_SELECTORS";
export const SET_SELECTOR_CONFIG_DEFAULT = "SET_SELECTOR_DEFAULT";
export const SET_SELECTOR_CONFIG = "SET_SELECTOR_CONFIG";
export const TOGGLE_ENABLED = "TOGGLE_ENABLED";
export const SET_PLUGIN = "SET_PLUGIN";